add checks for env secret

diff --git a/.github/workflows/full-release-template.yml b/.github/workflows/full-release-template.yml
--- a/.github/workflows/full-release-template.yml
+++ b/.github/workflows/full-release-template.yml
@@ -26,8 +26,11 @@ jobs:
       - name: Set up Docker
         uses: docker/setup-buildx-action@v2
 
-      - name: Check WIF_PROVIDER
+      - name: Debug WIF_PROVIDER directly
         run: echo "WIF_PROVIDER is '${{ secrets.WIF_PROVIDER }}'"
+
+      - name: Dump environment for WIF vars
+        run: env | grep WIF || echo "WIF not found"
         
       - name: Auth to GCP
         uses: google-github-actions/auth@v1
